import { Center, Heading, Skeleton } from "@chakra-ui/react";
import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";

import { useSpnFactorySymbol, useSpnFactoryName } from "~~/generated/wagmi";

const Home: NextPage = () => {
  const symbolQuery = useSpnFactorySymbol({
    address: "0x5FbDB2315678afecb367f032d93F642f64180aa3",
  });
  const nameQuery = useSpnFactoryName({
    address: "0x5FbDB2315678afecb367f032d93F642f64180aa3",
  });

  return (
    <>
      <Head>
        <title>RainbowKit App</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Center
        sx={{
          minH: "100vh",
        }}
      >
        <ConnectButton />

        <Skeleton isLoaded={symbolQuery.isFetched && nameQuery.isFetched}>
          <Heading>
            <>
              {nameQuery.data} ({symbolQuery.data})
            </>
          </Heading>
        </Skeleton>
      </Center>
    </>
  );
};

export default Home;
